import { PortfolioProject, PortfolioSkill } from './types'

export const staticProjects: PortfolioProject[] = [
  {
    id: 'proj-1',
    category: 'web',
    title_de: 'Hajj & Umrah Plattform',
    title_fr: 'Plateforme Hajj & Umrah',
    title_en: 'Hajj & Umrah Platform',
    title_ar: 'منصة الحج والعمرة',
    description_de: 'Vollständige Reiseplanungs-Plattform für Hajj und Umrah mit SEPA-Lastschrift, GiroCode, Buchungsverwaltung und mehrsprachigen Guides (DE/FR/EN/AR).',
    description_fr: 'Plateforme complète de planification de voyages pour le Hajj et la Omra avec prélèvement SEPA, GiroCode, gestion des réservations et guides multilingues.',
    description_en: 'Complete travel planning platform for Hajj and Umrah with SEPA direct debit, GiroCode, booking management, and multilingual guides (DE/FR/EN/AR).',
    description_ar: 'منصة كاملة لتخطيط رحلات الحج والعمرة مع الخصم المباشر SEPA و GiroCode وإدارة الحجوزات والأدلة متعددة اللغات.',
    tech_stack: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Docker'],
    github_url: 'https://github.com/fecbatino/hajj-umrah',
    live_url: 'https://hu.fechal-batakpale.com',
    screenshot_url: null,
    sort_order: 1,
    created_at: '2025-01-01',
  },
  {
    id: 'proj-2',
    category: 'web',
    title_de: 'Fechal Webapp',
    title_fr: 'Fechal Webapp',
    title_en: 'Fechal Webapp',
    title_ar: 'تطبيق فيشال',
    description_de: 'Mehrsprachige Portfolio-Webapp mit Next.js 16, Supabase, Ghost CMS, Theme-System und automatisiertem CI/CD-Deployment.',
    description_fr: 'Application web portfolio multilingue avec Next.js 16, Supabase, Ghost CMS, système de thème et déploiement CI/CD automatisé.',
    description_en: 'Multilingual portfolio webapp with Next.js 16, Supabase, Ghost CMS, theme system, and automated CI/CD deployment.',
    description_ar: 'تطبيق ويب متعدد اللغات مع Next.js 16 و Supabase و Ghost CMS ونظام السمات والنشر التلقائي CI/CD.',
    tech_stack: ['Next.js', 'TypeScript', 'Supabase', 'Docker', 'Playwright'],
    github_url: 'https://github.com/fecbatino/fechal-webapp',
    live_url: 'https://fechal-batakpale.com',
    screenshot_url: null,
    sort_order: 2,
    created_at: '2025-02-01',
  },
  {
    id: 'proj-3',
    category: 'ai',
    title_de: 'KI-Agenten-Orchestrierung (Hermes Agent)',
    title_fr: 'Orchestration d\'agents IA (Hermes Agent)',
    title_en: 'AI Agent Orchestration (Hermes Agent)',
    title_ar: 'تنسيق وكلاء الذكاء الاصطناعي (Hermes Agent)',
    description_de: 'Autonome KI-Agenten-Workflows mit Claude Code, n8n-Automation und OpenRouter-Multimodell-Routing für DevOps, Code-Review und Monitoring.',
    description_fr: 'Workflows autonomes d\'agents IA avec Claude Code, automation n8n et routage multimodèle OpenRouter pour DevOps, révision de code et monitoring.',
    description_en: 'Autonomous AI agent workflows with Claude Code, n8n automation, and OpenRouter multi-model routing for DevOps, code review, and monitoring.',
    description_ar: 'سير عمل وكلاء ذكاء اصطناعي مستقلين مع Claude Code وأتمتة n8n وتوجيه OpenRouter متعدد النماذج لـ DevOps ومراجعة الكود والمراقبة.',
    tech_stack: ['Claude Code', 'n8n', 'OpenRouter', 'Docker', 'PostgreSQL'],
    github_url: null,
    live_url: null,
    screenshot_url: null,
    sort_order: 3,
    created_at: '2025-03-01',
  },
  {
    id: 'proj-4',
    category: 'web',
    title_de: 'AIKF-KIOSK',
    title_fr: 'AIKF-KIOSK',
    title_en: 'AIKF-KIOSK',
    title_ar: 'كشك AIKF',
    description_de: 'Digitaler Infokiosk für den AIKF e.V. Nürnberg – mehrsprachige Vereinsinformationen und Mitglieder-Angebote auf einem Touchscreen-Terminal.',
    description_fr: 'Kiosque d\'information numérique pour l\'AIKF e.V. Nürnberg – informations associatives multilingues et offres pour les membres sur un terminal tactile.',
    description_en: 'Digital info kiosk for AIKF e.V. Nürnberg – multilingual association information and member offers on a touchscreen terminal.',
    description_ar: 'منصة معلومات رقمية لجمعية AIKF e.V. نورنبرغ – معلومات جمعوية متعددة اللغات وعروض للأعضاء على شاشة لمس.',
    tech_stack: ['Next.js', 'TypeScript', 'Docker', 'Nginx'],
    github_url: null,
    live_url: 'https://kiosk.fechal-batakpale.com',
    screenshot_url: null,
    sort_order: 4,
    created_at: '2025-04-01',
  },
  {
    id: 'proj-5',
    category: 'vereine',
    title_de: 'Hizbulazam',
    title_fr: 'Hizbulazam',
    title_en: 'Hizbulazam',
    title_ar: 'حزبالاظام',
    description_de: 'Informationsseite für Hizbulazam – islamische Bildungsinitiative mit mehrsprachigen Inhalten.',
    description_fr: 'Page d\'information pour Hizbulazam – initiative d\'éducation islamique avec contenu multilingue.',
    description_en: 'Information page for Hizbulazam – Islamic education initiative with multilingual content.',
    description_ar: 'صفحة معلومات لـ حزبالاظام – مبادرة تعليم إسلامي بمحتوى متعدد اللغات.',
    tech_stack: ['HTML', 'CSS', 'Docker', 'Nginx'],
    github_url: null,
    live_url: 'https://hza.fechal-batakpale.com',
    screenshot_url: null,
    sort_order: 5,
    created_at: '2025-05-01',
  },
]

export const staticSkills: PortfolioSkill[] = [
  { id: 'skill-1', name: 'TypeScript', category: 'frontend', sort_order: 1 },
  { id: 'skill-2', name: 'React', category: 'frontend', sort_order: 2 },
  { id: 'skill-3', name: 'Next.js', category: 'frontend', sort_order: 3 },
  { id: 'skill-4', name: 'Tailwind CSS', category: 'frontend', sort_order: 4 },
  { id: 'skill-5', name: 'Java Spring Boot', category: 'backend', sort_order: 5 },
  { id: 'skill-6', name: 'Node.js', category: 'backend', sort_order: 6 },
  { id: 'skill-7', name: 'PostgreSQL', category: 'backend', sort_order: 7 },
  { id: 'skill-8', name: 'Oracle DB', category: 'backend', sort_order: 8 },
  { id: 'skill-9', name: 'Docker', category: 'tools', sort_order: 9 },
  { id: 'skill-10', name: 'GitHub Actions', category: 'tools', sort_order: 10 },
  { id: 'skill-11', name: 'n8n', category: 'tools', sort_order: 11 },
  { id: 'skill-12', name: 'Supabase', category: 'tools', sort_order: 12 },
  { id: 'skill-13', name: 'Claude Code', category: 'ai', sort_order: 13 },
  { id: 'skill-14', name: 'OpenRouter', category: 'ai', sort_order: 14 },
  { id: 'skill-15', name: 'Ollama', category: 'ai', sort_order: 15 },
]