import { PortfolioProject, PortfolioSkill } from './types'

export const staticProjects: PortfolioProject[] = [
  {
    id: 'proj-1',
    category: 'web',
    title_de: 'Hajj & Umrah Plattform',
    title_fr: 'Plateforme Hajj & Umrah',
    title_en: 'Hajj & Umrah Platform',
    title_ar: 'منصة الحج والعمرة',
    description_de: 'Vollständige Reiseplanungs-Plattform für Hajj und Umrah für den AIKF e.V. Nürnberg. SEPA-Lastschrift, GiroCode-Generierung, multilinguales Buchungssystem mit 4 Sprachen (DE/FR/EN/AR).',
    description_fr: 'Plateforme complète de planification de voyages pour le Hajj et la Omra pour l\'AIKF e.V. Nürnberg. Prélèvement SEPA, génération de GiroCode, système de réservation multilingue en 4 langues.',
    description_en: 'Complete travel planning platform for Hajj and Umrah for AIKF e.V. Nürnberg. SEPA direct debit, GiroCode generation, multilingual booking system in 4 languages.',
    description_ar: 'منصة كاملة لتخطيط رحلات الحج والعمرة لجمعية AIKF e.V. نورنبرغ. الخصم المباشر SEPA وتوليد GiroCode ونظام حجز متعدد اللغات بأربع لغات.',
    tech_stack: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Docker', 'Evolution API'],
    github_url: 'https://github.com/fecbatino/hajj-umrah',
    live_url: 'https://hu.fechal-batakpale.com',
    screenshot_url: '/portfolio/hajj-umrah.png',
    sort_order: 1,
    created_at: '2025-01-01',
  },
  {
    id: 'proj-2',
    category: 'web',
    title_de: 'Fechal Webapp',
    title_fr: 'Fechal Webapp',
    title_en: 'Fechal Webapp',
    title_ar: 'تطبيق فيشال',
    description_de: 'Mehrsprachige Portfolio-Webapp (Next.js 16, 4 Sprachen DE/FR/EN/AR). Dark-Glassmorphism, CI/CD-Pipeline via GitHub Actions, E2E-Tests mit Playwright, Ghost CMS für Blog.',
    description_fr: 'Application web portfolio multilingue (Next.js 16, 4 langues). Dark-glassmorphism, pipeline CI/CD avec GitHub Actions, tests E2E avec Playwright, Ghost CMS pour le blog.',
    description_en: 'Multilingual portfolio webapp (Next.js 16, 4 languages DE/FR/EN/AR). Dark glassmorphism UI, CI/CD pipeline via GitHub Actions, E2E tests with Playwright, Ghost CMS for blog.',
    description_ar: 'تطبيق ويب متعدد اللغات (Next.js 16، 4 لغات). واجهة زجاجية داكنة، خط أنابيب CI/CD عبر GitHub Actions، اختبارات E2E مع Playwright، نظام Ghost CMS للمدونة.',
    tech_stack: ['Next.js 16', 'TypeScript', 'Supabase', 'Docker', 'Playwright', 'next-intl'],
    github_url: 'https://github.com/fecbatino/fechal-webapp',
    live_url: 'https://fechal-batakpale.com',
    screenshot_url: '/portfolio/fechal-webapp.png',
    sort_order: 2,
    created_at: '2025-02-01',
  },
  {
    id: 'proj-3',
    category: 'ai',
    title_de: 'KI-Agenten-Orchestrierung (Hermes Agent)',
    title_fr: 'Orchestration d\'agents IA (Hermes Agent)',
    title_en: 'AI Agent Orchestration (Hermes Agent)',
    title_ar: 'تنسيق وكلاء الذكاء الاصطناعي (Hermes Agent)',
    description_de: 'Autonomer KI-Agent für DevOps, Code-Review, Monitoring und CI/CD-Steuerung. Betreibt n8n-Workflows, OpenRouter-Multimodell-Routing und automatisierte Server-Health-Checks auf dem Hetzner-Stack.',
    description_fr: 'Agent IA autonome pour DevOps, révision de code, monitoring et pilotage CI/CD. Exploite des workflows n8n, routage multimodèle OpenRouter et checks de santé automatisés sur stack Hetzner.',
    description_en: 'Autonomous AI agent for DevOps, code review, monitoring, and CI/CD orchestration. Runs n8n workflows, OpenRouter multi-model routing, and automated server health checks on Hetzner stack.',
    description_ar: 'وكيل ذكاء اصطناعي مستقل لـ DevOps ومراجعة الكود والمراقبة وتنسيق CI/CD. يدير سير عمل n8n وتوجيه OpenRouter متعدد النماذج وفحوصات الصحة التلقائية على خادم Hetzner.',
    tech_stack: ['Claude Code', 'n8n', 'OpenRouter', 'Docker', 'PostgreSQL', 'Playwright'],
    github_url: null,
    live_url: null,
    screenshot_url: null,
    sort_order: 3,
    created_at: '2025-03-01',
  },
  {
    id: 'proj-4',
    category: 'web',
    title_de: 'AIKF-KIOSK',
    title_fr: 'AIKF-KIOSK',
    title_en: 'AIKF-KIOSK',
    title_ar: 'كشك AIKF',
    description_de: 'Digitaler Infokiosk für den AIKF e.V. Nürnberg auf einem Raspberry-Pi-Touchscreen. Mehrsprachige Vereinsinfo, Veranstaltungskalender und Mitgliederangebote – vollständig Docker-betrieben.',
    description_fr: 'Kiosque numérique pour l\'AIKF e.V. Nürnberg sur écran tactile Raspberry Pi. Infos associatives multilingues, calendrier d\'événements et offres membres – entièrement sous Docker.',
    description_en: 'Digital info kiosk for AIKF e.V. Nürnberg on a Raspberry Pi touchscreen. Multilingual association info, event calendar, and member offers – fully Docker-powered.',
    description_ar: 'منصة معلومات رقمية لجمعية AIKF e.V. نورنبرغ على شاشة Raspberry Pi تعمل باللمس. معلومات جمعوية متعددة اللغات وتقويم الفعاليات وعروض الأعضاء – تعمل بالكامل عبر Docker.',
    tech_stack: ['Next.js', 'TypeScript', 'Docker', 'Nginx', 'Raspberry Pi'],
    github_url: null,
    live_url: 'https://kiosk.fechal-batakpale.com',
    screenshot_url: '/portfolio/aikf-kiosk.png',
    sort_order: 4,
    created_at: '2025-04-01',
  },
  {
    id: 'proj-5',
    category: 'vereine',
    title_de: 'Hizbulazam',
    title_fr: 'Hizbulazam',
    title_en: 'Hizbulazam',
    title_ar: 'حزبالاظام',
    description_de: 'Informationsseite für die islamische Bildungsinitiative Hizbulazam. Responsives Design, mehrsprachige Inhalte (DE/FR/EN/AR), optimiert für schnelle Ladezeiten.',
    description_fr: 'Page d\'information pour l\'initiative d\'éducation islamique Hizbulazam. Design responsive, contenu multilingue, optimisé pour des temps de chargement rapides.',
    description_en: 'Information page for the Islamic education initiative Hizbulazam. Responsive design, multilingual content (DE/FR/EN/AR), optimized for fast loading.',
    description_ar: 'صفحة معلومات لمبادرة التعليم الإسلامي حزبالاظام. تصميم متجاوب، محتوى متعدد اللغات، محسّن للتحميل السريع.',
    tech_stack: ['HTML', 'CSS', 'JavaScript', 'Docker', 'Nginx'],
    github_url: null,
    live_url: 'https://hza.fechal-batakpale.com',
    screenshot_url: '/portfolio/hizbulazam.png',
    sort_order: 5,
    created_at: '2025-05-01',
  },
]

export const staticSkills: PortfolioSkill[] = [
  { id: 'skill-1', name: 'TypeScript', category: 'frontend', sort_order: 1 },
  { id: 'skill-2', name: 'React', category: 'frontend', sort_order: 2 },
  { id: 'skill-3', name: 'Next.js', category: 'frontend', sort_order: 3 },
  { id: 'skill-4', name: 'Tailwind CSS', category: 'frontend', sort_order: 4 },
  { id: 'skill-5', name: 'Java Spring Boot', category: 'backend', sort_order: 5 },
  { id: 'skill-6', name: 'Node.js', category: 'backend', sort_order: 6 },
  { id: 'skill-7', name: 'PostgreSQL', category: 'backend', sort_order: 7 },
  { id: 'skill-8', name: 'Oracle DB', category: 'backend', sort_order: 8 },
  { id: 'skill-9', name: 'Docker', category: 'tools', sort_order: 9 },
  { id: 'skill-10', name: 'GitHub Actions', category: 'tools', sort_order: 10 },
  { id: 'skill-11', name: 'n8n', category: 'tools', sort_order: 11 },
  { id: 'skill-12', name: 'Supabase', category: 'tools', sort_order: 12 },
  { id: 'skill-13', name: 'Claude Code', category: 'ai', sort_order: 13 },
  { id: 'skill-14', name: 'OpenRouter', category: 'ai', sort_order: 14 },
  { id: 'skill-15', name: 'Ollama', category: 'ai', sort_order: 15 },
]